/**
 * Seed Expanded Attractions Data
 * 中国各大城市名胜古迹和人文景点（扩充版）
 * 运行: npx tsx src/storage/database/seedExpandedAttractions.ts
 */

import { getDb } from '@/lib/db';
import { attractions } from "./shared/schema";

const EXPANDED_ATTRACTIONS = [
  // ==================== 北京 ====================
  {
    nameEn: "The Great Wall (Mutianyu)", nameZh: "慕田峪长城",
    descriptionEn: "Less crowded Great Wall section with beautiful mountain views and cable car access.",
    descriptionZh: "长城人少的一段，山景优美，可乘缆车。",
    category: "Historical", location: "Beijing", city: "Beijing",
    openingHours: "8:00-17:00", averageDuration: "3-4 hours",
    ticketPrice: "45", currency: "USD", rating: "4.8",
    isRecommendedForPatients: false, accessibilityFeatures: JSON.stringify(["Cable car access"]),
    tipsEn: "Cable car available. Avoid steep sections if mobility issues.",
    tipsZh: "有缆车。行动不便者避开陡峭路段。",
    isFeatured: true, isActive: true,
  },
  {
    nameEn: "Forbidden City (Palace Museum)", nameZh: "故宫博物院",
    descriptionEn: "Ming & Qing imperial palace, UNESCO site with 9,000+ rooms and priceless artifacts.",
    descriptionZh: "明清皇家宫殿，联合国教科文组织世界遗产，9,000多间房和珍贵文物。",
    category: "Historical", location: "Beijing", city: "Beijing",
    openingHours: "8:30-17:00", averageDuration: "3-4 hours",
    ticketPrice: "20", currency: "USD", rating: "4.9",
    isRecommendedForPatients: true, accessibilityFeatures: JSON.stringify(["Wheelchair accessible", "Ramps"]),
    tipsEn: "Book 7 days in advance. Flat terrain, wheelchair accessible.",
    tipsZh: "提前7天订票。地势平坦，轮椅可通行。",
    isFeatured: true, isActive: true,
  },
  {
    nameEn: "Temple of Heaven", nameZh: "天坛",
    descriptionEn: "Ming Dynasty temple complex for harvest prayers. UNESCO site with beautiful park.",
    descriptionZh: "明代祭坛建筑群，祈求丰收之处。联合国教科文组织世界遗产。",
    category: "Religious", location: "Beijing", city: "Beijing",
    openingHours: "6:00-22:00", averageDuration: "2-3 hours",
    ticketPrice: "15", currency: "USD", rating: "4.7",
    isRecommendedForPatients: true, accessibilityFeatures: JSON.stringify(["Wheelchair accessible", "Flat terrain"]),
    tipsEn: "Morning tai chi practice. Flat paths, excellent for patients.",
    tipsZh: "清晨有太极练习。平坦小路，非常适合患者。",
    isFeatured: true, isActive: true,
  },
  {
    nameEn: "Summer Palace", nameZh: "颐和园",
    descriptionEn: "Best-preserved imperial garden with Kunming Lake. UNESCO World Heritage site.",
    descriptionZh: "保存最完好的皇家园林，有昆明湖。联合国教科文组织世界遗产。",
    category: "Natural", location: "Beijing", city: "Beijing",
    openingHours: "6:30-18:00", averageDuration: "3-4 hours",
    ticketPrice: "10", currency: "USD", rating: "4.8",
    isRecommendedForPatients: true, accessibilityFeatures: JSON.stringify(["Wheelchair accessible", "Boat dock"]),
    tipsEn: "Boating on Kunming Lake. Wheelchair accessible main paths.",
    tipsZh: "昆明湖划船。主路轮椅可通行。",
    isFeatured: true, isActive: true,
  },
  {
    nameEn: "Lama Temple (Yonghe Temple)", nameZh: "雍和宫",
    descriptionEn: "Renowned Tibetan Buddhist temple with magnificent architecture and a 26m Buddha statue.",
    descriptionZh: "著名藏传佛教寺院，宏伟建筑和26米高佛像。",
    category: "Religious", location: "Beijing", city: "Beijing",
    openingHours: "9:00-16:00", averageDuration: "1-2 hours",
    ticketPrice: "8", currency: "USD", rating: "4.6",
    isRecommendedForPatients: true, accessibilityFeatures: JSON.stringify(["Wheelchair access to main hall"]),
    tipsEn: "Active worship place. Respectful silence appreciated.",
    tipsZh: "活跃的宗教场所，请保持安静。",
    isFeatured: false, isActive: true,
  },
  {
    nameEn: "Beihai Park", nameZh: "北海公园",
    descriptionEn: "Imperial garden from 10th century with white dagoba and beautiful lake views.",
    descriptionZh: "10世纪皇家园林，白塔和美丽湖景。",
    category: "Natural", location: "Beijing", city: "Beijing",
    openingHours: "6:30-21:00", averageDuration: "2 hours",
    ticketPrice: "5", currency: "USD", rating: "4.5",
    isRecommendedForPatients: true, accessibilityFeatures: JSON.stringify(["Wheelchair accessible", "Flat paths"]),
    tipsEn: "Rent a paddle boat. Flat and easy walking paths.",
    tipsZh: "可租脚踏船。平坦易行的步道。",
    isFeatured: false, isActive: true,
  },
  {
    nameEn: "National Museum of China", nameZh: "中国国家博物馆",
    descriptionEn: "World's largest museum with 1.05 million sq ft, showcasing Chinese history and art.",
    descriptionZh: "世界最大博物馆，面积105万平方英尺，展示中国历史和艺术。",
    category: "Cultural", location: "Beijing", city: "Beijing",
    openingHours: "9:00-17:00", averageDuration: "3-4 hours",
    ticketPrice: "0", currency: "USD", rating: "4.6",
    isRecommendedForPatients: true, accessibilityFeatures: JSON.stringify(["Wheelchair accessible", "Elevators"]),
    tipsEn: "Free admission. Wheelchair accessible, flat interior.",
    tipsZh: "免费入场。轮椅可通行，内部平坦。",
    isFeatured: false, isActive: true,
  },
  {
    nameEn: "Beijing Hutongs (Nanluoguxiang)", nameZh: "南锣鼓巷",
    descriptionEn: "Historic alleyways dating back to Yuan Dynasty, lined with shops, cafes and courtyard homes.",
    descriptionZh: "元代历史胡同，商店、咖啡馆和四合院林立。",
    category: "Cultural", location: "Beijing", city: "Beijing",
    openingHours: "All day", averageDuration: "2-3 hours",
    ticketPrice: "0", currency: "USD", rating: "4.4",
    isRecommendedForPatients: true, accessibilityFeatures: JSON.stringify(["Wheelchair accessible", "Flat paths"]),
    tipsEn: "Rickshaw tour available. Flat terrain, easy walking.",
    tipsZh: "可乘坐人力车游览。地势平坦。",
    isFeatured: false, isActive: true,
  },

  // ==================== 上海 ====================
  {
    nameEn: "The Bund", nameZh: "外滩",
    descriptionEn: "Iconic waterfront with colonial architecture and stunning Pudong skyline views.",
    descriptionZh: "标志性滨水区，殖民建筑和壮观浦东天际线。",
    category: "Modern", location: "Shanghai", city: "Shanghai",
    openingHours: "24 hours", averageDuration: "1-2 hours",
    ticketPrice: "0", currency: "USD", rating: "4.7",
    isRecommendedForPatients: true, accessibilityFeatures: JSON.stringify(["Wheelchair accessible", "Benches", "Elevator access"]),
    tipsEn: "Best at night. Flat promenade, fully accessible.",
    tipsZh: "夜晚最佳。平坦的滨江步道，完全无障碍。",
    isFeatured: true, isActive: true,
  },
  {
    nameEn: "Yu Garden (Yuyuan)", nameZh: "豫园",
    descriptionEn: "Classical Ming Dynasty garden with pavilions, rockeries, ponds and adjoining bazaar.",
    descriptionZh: "明代古典园林，亭台楼阁、假山池塘，相邻的豫园商场。",
    category: "Cultural", location: "Shanghai", city: "Shanghai",
    openingHours: "8:30-17:30", averageDuration: "1-2 hours",
    ticketPrice: "10", currency: "USD", rating: "4.5",
    isRecommendedForPatients: false, accessibilityFeatures: JSON.stringify(["Limited wheelchair access", "Steps"]),
    tipsEn: "Bazaar shopping nearby. Some uneven paths.",
    tipsZh: "附近商场可购物。部分路面不平。",
    isFeatured: true, isActive: true,
  },
  {
    nameEn: "Shanghai Tower", nameZh: "上海中心大厦",
    descriptionEn: "China's tallest building (632m) with world's fastest elevator and 118th floor observatory.",
    descriptionZh: "中国最高建筑（632米），世界最快电梯和118层观景台。",
    category: "Modern", location: "Shanghai", city: "Shanghai",
    openingHours: "9:00-21:00", averageDuration: "1-2 hours",
    ticketPrice: "40", currency: "USD", rating: "4.6",
    isRecommendedForPatients: false, accessibilityFeatures: JSON.stringify(["Wheelchair accessible", "High-speed elevators"]),
    tipsEn: "World's fastest elevator. Clear day offers best views.",
    tipsZh: "世界最快电梯。晴天视野最佳。",
    isFeatured: true, isActive: true,
  },
  {
    nameEn: "Zhujiajiao Water Town", nameZh: "朱家角古镇",
    descriptionEn: "Ancient water town with 1,700 years of history, canals, stone bridges and Ming architecture.",
    descriptionZh: "1,700年历史古镇，水道、石桥和明代建筑。",
    category: "Historical", location: "Shanghai", city: "Shanghai",
    openingHours: "8:30-16:30", averageDuration: "3-4 hours",
    ticketPrice: "10", currency: "USD", rating: "4.4",
    isRecommendedForPatients: false, accessibilityFeatures: JSON.stringify(["Boat access", "Stone paths"]),
    tipsEn: "Boat ride through canals. Some uneven stone paths.",
    tipsZh: "乘船游览水道。部分石板路不平。",
    isFeatured: false, isActive: true,
  },
  {
    nameEn: "Nanjing Road Pedestrian Street", nameZh: "南京路步行街",
    descriptionEn: "China's premier shopping street with 100+ years of history and iconic neon lights.",
    descriptionZh: "中国首屈一指的购物街，100多年历史和标志性霓虹灯。",
    category: "Modern", location: "Shanghai", city: "Shanghai",
    openingHours: "All day", averageDuration: "2-3 hours",
    ticketPrice: "0", currency: "USD", rating: "4.3",
    isRecommendedForPatients: true, accessibilityFeatures: JSON.stringify(["Wheelchair accessible", "Flat surface"]),
    tipsEn: "Crowded on weekends. Flat, easy walking.",
    tipsZh: "周末拥挤。平坦易行。",
    isFeatured: false, isActive: true,
  },
  {
    nameEn: "Oriental Pearl Tower", nameZh: "东方明珠塔",
    descriptionEn: "Iconic Shanghai landmark (468m) with observation floors, revolving restaurant and museum.",
    descriptionZh: "上海标志性地标（468米），观景层、旋转餐厅和博物馆。",
    category: "Modern", location: "Shanghai", city: "Shanghai",
    openingHours: "8:00-22:00", averageDuration: "2 hours",
    ticketPrice: "30", currency: "USD", rating: "4.4",
    isRecommendedForPatients: false, accessibilityFeatures: JSON.stringify(["Wheelchair accessible", "Elevators"]),
    tipsEn: "Night views fantastic. Glass-floor observation deck thrilling.",
    tipsZh: "夜景极佳。玻璃观景台令人兴奋。",
    isFeatured: false, isActive: true,
  },

  // ==================== 西安 ====================
  {
    nameEn: "Terracotta Army Museum", nameZh: "秦始皇兵马俑博物馆",
    descriptionEn: "UNESCO site with 8,000+ life-size terracotta warriors guarding China's first emperor.",
    descriptionZh: "联合国教科文组织遗址，8,000多个真人大小的兵马俑守卫中国第一位皇帝。",
    category: "Historical", location: "Xi'an", city: "Xi'an",
    openingHours: "8:30-18:00", averageDuration: "3-4 hours",
    ticketPrice: "25", currency: "USD", rating: "4.9",
    isRecommendedForPatients: true, accessibilityFeatures: JSON.stringify(["Wheelchair accessible", "Ramps"]),
    tipsEn: "Hire a guide. Wheelchair accessible main pits.",
    tipsZh: "雇导游了解历史。主坑轮椅可通行。",
    isFeatured: true, isActive: true,
  },
  {
    nameEn: "Xi'an City Wall", nameZh: "西安城墙",
    descriptionEn: "China's best-preserved ancient city wall (13.7km). Cycle or walk the full perimeter.",
    descriptionZh: "中国保存最完好的古城墙（13.7公里）。可骑行或步行全程。",
    category: "Historical", location: "Xi'an", city: "Xi'an",
    openingHours: "8:00-22:00", averageDuration: "2-3 hours",
    ticketPrice: "12", currency: "USD", rating: "4.6",
    isRecommendedForPatients: false, accessibilityFeatures: JSON.stringify(["Bike rentals", "Limited wheelchair access"]),
    tipsEn: "Rent a bike to cycle. Sunset views spectacular.",
    tipsZh: "租自行车骑行。日落景色壮观。",
    isFeatured: true, isActive: true,
  },
  {
    nameEn: "Big Wild Goose Pagoda", nameZh: "大雁塔",
    descriptionEn: "Tang Dynasty Buddhist pagoda (652 AD) symbol of Xi'an with evening light shows.",
    descriptionZh: "唐代佛教宝塔（公元652年），西安象征，有晚间灯光秀。",
    category: "Religious", location: "Xi'an", city: "Xi'an",
    openingHours: "8:00-17:30", averageDuration: "1-2 hours",
    ticketPrice: "10", currency: "USD", rating: "4.5",
    isRecommendedForPatients: true, accessibilityFeatures: JSON.stringify(["Elevator to certain levels"]),
    tipsEn: "Evening light show in North Square. Elevator available.",
    tipsZh: "北广场晚间灯光秀。有电梯。",
    isFeatured: true, isActive: true,
  },
  {
    nameEn: "Muslim Quarter (Huimin Street)", nameZh: "回民街",
    descriptionEn: "Vibrant Islamic quarter with traditional architecture, Great Mosque, and famous street food.",
    descriptionZh: "充满活力的伊斯兰区，传统建筑、大清真寺和著名街头美食。",
    category: "Cultural", location: "Xi'an", city: "Xi'an",
    openingHours: "All day", averageDuration: "2-3 hours",
    ticketPrice: "0", currency: "USD", rating: "4.4",
    isRecommendedForPatients: true, accessibilityFeatures: JSON.stringify(["Wheelchair accessible", "Narrow passages"]),
    tipsEn: "Try local snacks. Crowded, flat terrain.",
    tipsZh: "尝试当地小吃。拥挤，地势平坦。",
    isFeatured: false, isActive: true,
  },
  {
    nameEn: "Shaanxi History Museum", nameZh: "陕西历史博物馆",
    descriptionEn: "One of China's top museums with 370,000+ artifacts spanning over 1 million years.",
    descriptionZh: "中国顶级博物馆之一，37万多件文物跨越100多万年。",
    category: "Cultural", location: "Xi'an", city: "Xi'an",
    openingHours: "8:30-18:00", averageDuration: "2-3 hours",
    ticketPrice: "5", currency: "USD", rating: "4.7",
    isRecommendedForPatients: true, accessibilityFeatures: JSON.stringify(["Wheelchair accessible", "Elevators"]),
    tipsEn: "Book free tickets early. Wheelchair accessible.",
    tipsZh: "提前预订免费票。轮椅可通行。",
    isFeatured: false, isActive: true,
  },

  // ==================== 成都 ====================
  {
    nameEn: "Panda Breeding Research Base", nameZh: "成都大熊猫繁育研究基地",
    descriptionEn: "World's most important panda conservation center with 100+ giant pandas.",
    descriptionZh: "世界最重要的大熊猫保护中心，100多只大熊猫。",
    category: "Natural", location: "Chengdu", city: "Chengdu",
    openingHours: "7:30-18:00", averageDuration: "3-4 hours",
    ticketPrice: "15", currency: "USD", rating: "4.8",
    isRecommendedForPatients: true, accessibilityFeatures: JSON.stringify(["Wheelchair accessible", "Golf cart"]),
    tipsEn: "Morning visit for active pandas. Golf cart available.",
    tipsZh: "清晨游览，熊猫最活跃。有高尔夫球车。",
    isFeatured: true, isActive: true,
  },
  {
    nameEn: "Jinli Ancient Street", nameZh: "锦里古街",
    descriptionEn: "Qing Dynasty-style pedestrian street with traditional snacks, crafts and tea houses.",
    descriptionZh: "清代风格步行街，有传统小吃、手工艺品和茶馆。",
    category: "Cultural", location: "Chengdu", city: "Chengdu",
    openingHours: "All day", averageDuration: "1-2 hours",
    ticketPrice: "0", currency: "USD", rating: "4.5",
    isRecommendedForPatients: true, accessibilityFeatures: JSON.stringify(["Wheelchair accessible", "Flat terrain"]),
    tipsEn: "Try spicy snacks. Flat terrain.",
    tipsZh: "尝试辣味小吃。地势平坦。",
    isFeatured: true, isActive: true,
  },
  {
    nameEn: "Wuhou Shrine", nameZh: "武侯祠",
    descriptionEn: "Temple honoring Zhuge Liang, legendary Three Kingdoms strategist. Beautiful gardens.",
    descriptionZh: "纪念三国传奇战略家诸葛亮的庙宇。美丽的花园。",
    category: "Historical", location: "Chengdu", city: "Chengdu",
    openingHours: "8:00-18:00", averageDuration: "1-2 hours",
    ticketPrice: "10", currency: "USD", rating: "4.4",
    isRecommendedForPatients: true, accessibilityFeatures: JSON.stringify(["Wheelchair accessible", "Flat paths"]),
    tipsEn: "Beautiful gardens. Flat and peaceful.",
    tipsZh: "美丽的花园。平坦宁静。",
    isFeatured: false, isActive: true,
  },
  {
    nameEn: "Leshan Giant Buddha", nameZh: "乐山大佛",
    descriptionEn: "World's largest stone Buddha (71m), carved in 8th century. UNESCO World Heritage site.",
    descriptionZh: "世界最大石佛（71米），8世纪雕刻。联合国教科文组织世界遗产。",
    category: "Religious", location: "Chengdu", city: "Chengdu",
    openingHours: "7:30-18:30", averageDuration: "4-5 hours",
    ticketPrice: "20", currency: "USD", rating: "4.7",
    isRecommendedForPatients: false, accessibilityFeatures: JSON.stringify(["Limited accessibility", "Many stairs"]),
    tipsEn: "Go down to Buddha's feet. Many stairs, worth it.",
    tipsZh: "下到佛脚处。很多楼梯，值得。",
    isFeatured: true, isActive: true,
  },

  // ==================== 杭州 ====================
  {
    nameEn: "West Lake (Xi Hu)", nameZh: "西湖",
    descriptionEn: "UNESCO World Heritage site, symbol of Hangzhou with ten iconic scenic spots.",
    descriptionZh: "联合国教科文组织世界遗产，杭州象征，十景闻名。",
    category: "Natural", location: "Hangzhou", city: "Hangzhou",
    openingHours: "All day", averageDuration: "4-5 hours",
    ticketPrice: "0", currency: "USD", rating: "4.9",
    isRecommendedForPatients: true, accessibilityFeatures: JSON.stringify(["Wheelchair accessible", "Boat access"]),
    tipsEn: "Boat tour, bike rental. Spring and autumn best.",
    tipsZh: "乘船游览，租自行车。春秋两季最佳。",
    isFeatured: true, isActive: true,
  },
  {
    nameEn: "Lingyin Temple (Soul's Retreat)", nameZh: "灵隐寺",
    descriptionEn: "One of China's oldest Buddhist temples (326 AD) with stunning Feilai Peak carvings.",
    descriptionZh: "中国最古老佛教寺庙之一（公元326年），飞来峰石雕令人惊叹。",
    category: "Religious", location: "Hangzhou", city: "Hangzhou",
    openingHours: "7:00-18:00", averageDuration: "2-3 hours",
    ticketPrice: "7", currency: "USD", rating: "4.6",
    isRecommendedForPatients: false, accessibilityFeatures: JSON.stringify(["Partial access", "Steep paths"]),
    tipsEn: "Feilai Peak carvings nearby. Some stairs.",
    tipsZh: "附近的飞来峰石雕。需要爬一些楼梯。",
    isFeatured: true, isActive: true,
  },
  {
    nameEn: "Hefang Street", nameZh: "河坊街",
    descriptionEn: "Historic pedestrian street with traditional shops, tea houses and local Hangzhou snacks.",
    descriptionZh: "历史步行街，传统商店、茶馆和杭州当地小吃。",
    category: "Cultural", location: "Hangzhou", city: "Hangzhou",
    openingHours: "All day", averageDuration: "1-2 hours",
    ticketPrice: "0", currency: "USD", rating: "4.3",
    isRecommendedForPatients: true, accessibilityFeatures: JSON.stringify(["Wheelchair accessible", "Flat surface"]),
    tipsEn: "Try Longjing tea. Flat, easy walking.",
    tipsZh: "尝试龙井茶。平坦易行。",
    isFeatured: false, isActive: true,
  },

  // ==================== 苏州 ====================
  {
    nameEn: "Humble Administrator's Garden", nameZh: "拙政园",
    descriptionEn: "UNESCO site, finest classical garden in southern China with pavilions and lotus ponds.",
    descriptionZh: "联合国教科文组织遗址，中国南方最精美古典园林，亭台和荷塘。",
    category: "Cultural", location: "Suzhou", city: "Suzhou",
    openingHours: "7:30-17:30", averageDuration: "2-3 hours",
    ticketPrice: "12", currency: "USD", rating: "4.8",
    isRecommendedForPatients: false, tipsEn: "Best in spring/autumn. Some uneven paths.",
    tipsZh: "春秋两季最佳。部分路面不平。",
    accessibilityFeatures: JSON.stringify(["Limited wheelchair access"]),
    isFeatured: true, isActive: true,
  },
  {
    nameEn: "Tiger Hill", nameZh: "虎丘",
    descriptionEn: "2,500-year-old hill with leaning pagoda (China's Leaning Tower), gardens and historic sites.",
    descriptionZh: "2,500年历史名山，斜塔（中国比萨斜塔），花园和历史遗迹。",
    category: "Historical", location: "Suzhou", city: "Suzhou",
    openingHours: "7:30-18:00", averageDuration: "2 hours",
    ticketPrice: "10", currency: "USD", rating: "4.5",
    isRecommendedForPatients: false, tipsEn: "See the leaning pagoda. Some stairs.",
    tipsZh: "看斜塔。有些楼梯。",
    accessibilityFeatures: JSON.stringify(["Partial access"]),
    isFeatured: false, isActive: true,
  },
  {
    nameEn: "Pingjiang Road Historic District", nameZh: "平江路历史街区",
    descriptionEn: "Ancient canal-side street with traditional architecture, tea houses and boutique shops.",
    descriptionZh: "古老的运河边街道，传统建筑、茶馆和精品店。",
    category: "Cultural", location: "Suzhou", city: "Suzhou",
    openingHours: "All day", averageDuration: "1-2 hours",
    ticketPrice: "0", currency: "USD", rating: "4.4",
    isRecommendedForPatients: true, tipsEn: "Gondola ride. Flat scenic walkway.",
    tipsZh: "乘船游览。平坦风景步道。",
    accessibilityFeatures: JSON.stringify(["Wheelchair accessible", "Flat paths", "Boat access"]),
    isFeatured: true, isActive: true,
  },

  // ==================== 广州 ====================
  {
    nameEn: "Canton Tower", nameZh: "广州塔（小蛮腰）",
    descriptionEn: "China's tallest TV tower (600m) with observation decks and thrilling sky drop ride.",
    descriptionZh: "中国最高电视塔（600米），观景台和极速云霄。",
    category: "Modern", location: "Guangzhou", city: "Guangzhou",
    openingHours: "9:00-23:00", averageDuration: "2-3 hours",
    ticketPrice: "30", currency: "USD", rating: "4.6",
    isRecommendedForPatients: false, tipsEn: "Evening Pearl River views.",
    tipsZh: "夜晚珠江景色。",
    accessibilityFeatures: JSON.stringify(["Wheelchair accessible", "Elevators"]),
    isFeatured: true, isActive: true,
  },
  {
    nameEn: "Chen Clan Ancestral Hall", nameZh: "陈家祠",
    descriptionEn: "Qing Dynasty ancestral temple famous for Cantonese wood carvings and architecture.",
    descriptionZh: "清代宗祠，以广府木雕和建筑艺术闻名。",
    category: "Cultural", location: "Guangzhou", city: "Guangzhou",
    openingHours: "8:30-17:30", averageDuration: "1-2 hours",
    ticketPrice: "8", currency: "USD", rating: "4.5",
    isRecommendedForPatients: true, tipsEn: "Intricate wood carvings. Flat terrain.",
    tipsZh: "精细木雕。地势平坦。",
    accessibilityFeatures: JSON.stringify(["Wheelchair accessible"]),
    isFeatured: true, isActive: true,
  },
  {
    nameEn: "Shamian Island", nameZh: "沙面岛",
    descriptionEn: "Former European concession with colonial architecture, parks, cafes and tree-lined streets.",
    descriptionZh: "前欧洲租界，殖民建筑、公园、咖啡馆和林荫道。",
    category: "Historical", location: "Guangzhou", city: "Guangzhou",
    openingHours: "All day", averageDuration: "2 hours",
    ticketPrice: "0", currency: "USD", rating: "4.4",
    isRecommendedForPatients: true, tipsEn: "Photogenic European buildings. Flat walk.",
    tipsZh: "上镜的欧洲建筑。平坦步行。",
    accessibilityFeatures: JSON.stringify(["Wheelchair accessible", "Flat terrain", "Benches"]),
    isFeatured: false, isActive: true,
  },

  // ==================== 南京 ====================
  {
    nameEn: "Sun Yat-sen Mausoleum", nameZh: "中山陵",
    descriptionEn: "Resting place of Dr. Sun Yat-sen with 392 steps and impressive architecture.",
    descriptionZh: "孙中山先生安息之地，392级台阶，建筑宏伟。",
    category: "Historical", location: "Nanjing", city: "Nanjing",
    openingHours: "8:30-17:00", averageDuration: "2-3 hours",
    ticketPrice: "0", currency: "USD", rating: "4.6",
    isRecommendedForPatients: false, tipsEn: "Many stairs. Shuttle bus available.",
    tipsZh: "很多楼梯。有接驳巴士。",
    accessibilityFeatures: JSON.stringify(["Shuttle bus", "Limited wheelchair access"]),
    isFeatured: true, isActive: true,
  },
  {
    nameEn: "Confucius Temple (Fuzimiao)", nameZh: "夫子庙",
    descriptionEn: "Complex of temples and markets along Qinhuai River. Historic cultural and shopping center.",
    descriptionZh: "秦淮河边寺庙和市场建筑群。历史文化商业中心。",
    category: "Cultural", location: "Nanjing", city: "Nanjing",
    openingHours: "All day", averageDuration: "2-3 hours",
    ticketPrice: "5", currency: "USD", rating: "4.4",
    isRecommendedForPatients: true, tipsEn: "Try local snacks. Evening river cruise.",
    tipsZh: "尝试小吃。推荐晚间秦淮河游船。",
    accessibilityFeatures: JSON.stringify(["Wheelchair accessible", "Flat paths"]),
    isFeatured: false, isActive: true,
  },
  {
    nameEn: "Nanjing City Wall (Zhonghua Gate)", nameZh: "南京城墙（中华门）",
    descriptionEn: "China's most impressive city wall gate with massive garrison complex. Walk on top.",
    descriptionZh: "中国最壮观的城门，有庞大军营建筑群，可在城墙上行走。",
    category: "Historical", location: "Nanjing", city: "Nanjing",
    openingHours: "8:00-18:00", averageDuration: "1-2 hours",
    ticketPrice: "6", currency: "USD", rating: "4.5",
    isRecommendedForPatients: true, tipsEn: "Walk on top. Flat, impressive.",
    tipsZh: "在城墙上行走。平坦壮观。",
    accessibilityFeatures: JSON.stringify(["Wheelchair accessible", "Ramp access"]),
    isFeatured: false, isActive: true,
  },

  // ==================== 武汉 ====================
  {
    nameEn: "Yellow Crane Tower", nameZh: "黄鹤楼",
    descriptionEn: "Iconic tower on Snake Hill, one of China's Four Great Towers with Yangtze River views.",
    descriptionZh: "蛇山上的标志性建筑，中国四大名楼之一，长江美景。",
    category: "Historical", location: "Wuhan", city: "Wuhan",
    openingHours: "8:00-18:00", averageDuration: "1-2 hours",
    ticketPrice: "10", currency: "USD", rating: "4.5",
    isRecommendedForPatients: false, tipsEn: "Elevator available. Great river views.",
    tipsZh: "有电梯。壮观的江景。",
    accessibilityFeatures: JSON.stringify(["Elevator", "Some stairs"]),
    isFeatured: true, isActive: true,
  },
  {
    nameEn: "East Lake (Donghu) Scenic Area", nameZh: "东湖风景区",
    descriptionEn: "China's largest urban lake with botanical gardens, cherry blossoms and biking trails.",
    descriptionZh: "中国最大城中湖，植物园、樱花和自行车道。",
    category: "Natural", location: "Wuhan", city: "Wuhan",
    openingHours: "7:00-19:00", averageDuration: "3-4 hours",
    ticketPrice: "5", currency: "USD", rating: "4.4",
    isRecommendedForPatients: true, tipsEn: "Rent a bike. Spring cherry blossoms.",
    tipsZh: "租自行车。春季樱花。",
    accessibilityFeatures: JSON.stringify(["Wheelchair accessible", "Bike rentals"]),
    isFeatured: false, isActive: true,
  },
  {
    nameEn: "Wuhan Yangtze River Bridge", nameZh: "武汉长江大桥",
    descriptionEn: "First bridge over Yangtze River (1957), double-deck with road and railway. Walk across.",
    descriptionZh: "长江第一桥（1957年），公路铁路双层桥，可行走穿越。",
    category: "Modern", location: "Wuhan", city: "Wuhan",
    openingHours: "All day", averageDuration: "1 hour",
    ticketPrice: "0", currency: "USD", rating: "4.3",
    isRecommendedForPatients: true, tipsEn: "Walk across for views. Flat sidewalk.",
    tipsZh: "步行穿越观景。平坦人行道。",
    accessibilityFeatures: JSON.stringify(["Wheelchair accessible", "Flat surface"]),
    isFeatured: false, isActive: true,
  },

  // ==================== 深圳 ====================
  {
    nameEn: "Window of the World", nameZh: "世界之窗",
    descriptionEn: "Theme park with 130+ miniature replicas of world-famous landmarks.",
    descriptionZh: "主题公园，130多个世界著名地标微缩复制品。",
    category: "Entertainment", location: "Shenzhen", city: "Shenzhen",
    openingHours: "9:00-22:30", averageDuration: "6-8 hours",
    ticketPrice: "50", currency: "USD", rating: "4.4",
    isRecommendedForPatients: true, tipsEn: "Evening shows spectacular. Comfortable shoes.",
    tipsZh: "晚间表演壮观。穿舒适鞋子。",
    accessibilityFeatures: JSON.stringify(["Wheelchair accessible", "Stroller rental"]),
    isFeatured: true, isActive: true,
  },
  {
    nameEn: "Splendid China Folk Village", nameZh: "锦绣中华民俗村",
    descriptionEn: "82 miniature replicas of China's landmarks with ethnic dance shows.",
    descriptionZh: "82个中国地标微缩模型，民族舞蹈表演。",
    category: "Cultural", location: "Shenzhen", city: "Shenzhen",
    openingHours: "10:00-21:00", averageDuration: "4-6 hours",
    ticketPrice: "35", currency: "USD", rating: "4.3",
    isRecommendedForPatients: true, tipsEn: "Ethnic dance shows. Shuttle bus.",
    tipsZh: "民族舞蹈表演。穿梭巴士。",
    accessibilityFeatures: JSON.stringify(["Wheelchair accessible", "Shuttle bus"]),
    isFeatured: false, isActive: true,
  },
  {
    nameEn: "OCT-LOFT Creative Park", nameZh: "华侨城创意文化园",
    descriptionEn: "Creative arts district in former factory buildings galleries, cafes and boutiques.",
    descriptionZh: "旧厂房改造的创意艺术区，画廊、咖啡馆和精品店。",
    category: "Modern", location: "Shenzhen", city: "Shenzhen",
    openingHours: "10:00-22:00", averageDuration: "2-3 hours",
    ticketPrice: "0", currency: "USD", rating: "4.3",
    isRecommendedForPatients: true, tipsEn: "Weekend art markets. Flat walking.",
    tipsZh: "周末艺术市集。平坦步行。",
    accessibilityFeatures: JSON.stringify(["Wheelchair accessible", "Flat terrain"]),
    isFeatured: false, isActive: true,
  },

  // ==================== 天津 ====================
  {
    nameEn: "Tianjin Eye (Yongle Bridge)", nameZh: "天津之眼",
    descriptionEn: "World's only bridge-mounted Ferris wheel (120m) over Haihe River.",
    descriptionZh: "世界唯一建在桥上的摩天轮（120米），横跨海河。",
    category: "Modern", location: "Tianjin", city: "Tianjin",
    openingHours: "9:30-21:30", averageDuration: "1 hour",
    ticketPrice: "15", currency: "USD", rating: "4.5",
    isRecommendedForPatients: false, tipsEn: "Night views beautiful. Wheelchair accessible.",
    tipsZh: "夜景美丽。轮椅可通行。",
    accessibilityFeatures: JSON.stringify(["Wheelchair accessible"]),
    isFeatured: true, isActive: true,
  },
  {
    nameEn: "Ancient Culture Street (Gu Wenhua Jie)", nameZh: "古文化街",
    descriptionEn: "Traditional street with Qing Dynasty architecture, folk art shops and local snacks.",
    descriptionZh: "清代建筑风格传统街道，民间艺术店和当地小吃。",
    category: "Cultural", location: "Tianjin", city: "Tianjin",
    openingHours: "9:00-20:00", averageDuration: "1-2 hours",
    ticketPrice: "0", currency: "USD", rating: "4.3",
    isRecommendedForPatients: true, tipsEn: "Traditional crafts. Flat easy walk.",
    tipsZh: "传统手工艺品。平坦易行。",
    accessibilityFeatures: JSON.stringify(["Wheelchair accessible"]),
    isFeatured: false, isActive: true,
  },

  // ==================== 青岛 ====================
  {
    nameEn: "Zhan Qiao (Pier) & Little Qingdao", nameZh: "栈桥与小青岛",
    descriptionEn: "Iconic Qingdao landmark extending into the sea with Huilan Pavilion at the end.",
    descriptionZh: "青岛标志性景点，延伸入海，尽头有回澜阁。",
    category: "Modern", location: "Qingdao", city: "Qingdao",
    openingHours: "All day", averageDuration: "1-2 hours",
    ticketPrice: "0", currency: "USD", rating: "4.5",
    isRecommendedForPatients: true, tipsEn: "Sunset views. Flat, seaside walk.",
    tipsZh: "日落景色。平坦海滨步道。",
    accessibilityFeatures: JSON.stringify(["Wheelchair accessible", "Flat surface"]),
    isFeatured: true, isActive: true,
  },
  {
    nameEn: "Badaguan (Eight Passes) Scenic Area", nameZh: "八大关风景区",
    descriptionEn: "Beautiful area with European-style villas, tree-lined streets and beaches.",
    descriptionZh: "美丽的欧洲风格别墅区，林荫道和海滩。",
    category: "Natural", location: "Qingdao", city: "Qingdao",
    openingHours: "All day", averageDuration: "2-3 hours",
    ticketPrice: "0", currency: "USD", rating: "4.6",
    isRecommendedForPatients: true, tipsEn: "Spring cherry blossoms. Flat walking paths.",
    tipsZh: "春季樱花。平坦步道。",
    accessibilityFeatures: JSON.stringify(["Wheelchair accessible", "Flat paths"]),
    isFeatured: false, isActive: true,
  },

  // ==================== 厦门 ====================
  {
    nameEn: "Gulangyu Island", nameZh: "鼓浪屿",
    descriptionEn: "Car-free island with colonial architecture, piano museum and beautiful beaches.",
    descriptionZh: "无车岛，殖民建筑、钢琴博物馆和美丽海滩。",
    category: "Natural", location: "Xiamen", city: "Xiamen",
    openingHours: "8:00-18:00", averageDuration: "4-5 hours",
    ticketPrice: "10", currency: "USD", rating: "4.6",
    isRecommendedForPatients: false, tipsEn: "Ferry required. Walking island.",
    tipsZh: "需乘渡轮。步行岛屿。",
    accessibilityFeatures: JSON.stringify(["Ferry access", "Walking required"]),
    isFeatured: true, isActive: true,
  },
  {
    nameEn: "Nanputuo Temple", nameZh: "南普陀寺",
    descriptionEn: "Famous Buddhist temple at the foot of Wulao Peak with mountain climbing paths.",
    descriptionZh: "著名佛教寺庙，位于五老峰脚下，有登山道。",
    category: "Religious", location: "Xiamen", city: "Xiamen",
    openingHours: "8:00-17:00", averageDuration: "1-2 hours",
    ticketPrice: "0", currency: "USD", rating: "4.4",
    isRecommendedForPatients: true, tipsEn: "Free admission. Flat main area.",
    tipsZh: "免费入场。主要区域平坦。",
    accessibilityFeatures: JSON.stringify(["Partial wheelchair access"]),
    isFeatured: false, isActive: true,
  },

  // ==================== 重庆 ====================
  {
    nameEn: "Hongya Cave (Hongyadong)", nameZh: "洪崖洞",
    descriptionEn: "Spectacular 11-story stilt house complex with restaurants and shops by Jialing River.",
    descriptionZh: "壮观的11层吊脚楼建筑群，嘉陵江边的餐厅和商店。",
    category: "Cultural", location: "Chongqing", city: "Chongqing",
    openingHours: "10:00-23:00", averageDuration: "1-2 hours",
    ticketPrice: "0", currency: "USD", rating: "4.6",
    isRecommendedForPatients: false, tipsEn: "Night views magical. Elevator between floors.",
    tipsZh: "夜景如梦幻。层间有电梯。",
    accessibilityFeatures: JSON.stringify(["Elevators", "Accessible main areas"]),
    isFeatured: true, isActive: true,
  },
  {
    nameEn: "Three Gorges Museum", nameZh: "三峡博物馆",
    descriptionEn: "Museum covering the history, culture and engineering of the Three Gorges Dam region.",
    descriptionZh: "展示三峡大坝区域历史、文化和工程。",
    category: "Cultural", location: "Chongqing", city: "Chongqing",
    openingHours: "9:00-17:00", averageDuration: "2-3 hours",
    ticketPrice: "0", currency: "USD", rating: "4.5",
    isRecommendedForPatients: true, tipsEn: "Free. Wheelchair accessible. Very informative.",
    tipsZh: "免费。轮椅可通行。信息丰富。",
    accessibilityFeatures: JSON.stringify(["Wheelchair accessible", "Elevators"]),
    isFeatured: false, isActive: true,
  },

  // ==================== 昆明 ====================
  {
    nameEn: "Stone Forest (Shilin)", nameZh: "石林",
    descriptionEn: "UNESCO site with spectacular karst stone formations resembling a forest of stone.",
    descriptionZh: "联合国教科文组织遗址，壮观的喀斯特石林景观。",
    category: "Natural", location: "Kunming", city: "Kunming",
    openingHours: "8:00-18:00", averageDuration: "4-5 hours",
    ticketPrice: "25", currency: "USD", rating: "4.6",
    isRecommendedForPatients: false, tipsEn: "Shuttle bus inside. Uneven terrain.",
    tipsZh: "内有穿梭巴士。地面不平。",
    accessibilityFeatures: JSON.stringify(["Shuttle bus", "Limited wheelchair access"]),
    isFeatured: true, isActive: true,
  },
  {
    nameEn: "Yunnan Nationalities Village", nameZh: "云南民族村",
    descriptionEn: "Open-air museum showcasing 25 ethnic minority cultures with traditional buildings and shows.",
    descriptionZh: "露天博物馆，展示25个少数民族文化，传统建筑和表演。",
    category: "Cultural", location: "Kunming", city: "Kunming",
    openingHours: "8:30-18:00", averageDuration: "3-4 hours",
    ticketPrice: "12", currency: "USD", rating: "4.4",
    isRecommendedForPatients: true, tipsEn: "Ethnic shows. Flat walking paths.",
    tipsZh: "民族表演。平坦步道。",
    accessibilityFeatures: JSON.stringify(["Wheelchair accessible", "Flat paths"]),
    isFeatured: false, isActive: true,
  },

  // ==================== 长沙 ====================
  {
    nameEn: "Yuelu Mountain & Aiwan Pavilion", nameZh: "岳麓山·爱晚亭",
    descriptionEn: "Historic mountain with ancient academy, pavilion and panoramic city views.",
    descriptionZh: "历史名山，岳麓书院、爱晚亭和城市全景。",
    category: "Natural", location: "Changsha", city: "Changsha",
    openingHours: "6:00-22:00", averageDuration: "3-4 hours",
    ticketPrice: "0", currency: "USD", rating: "4.5",
    isRecommendedForPatients: false, tipsEn: "Cable car available. Autumn leaves spectacular.",
    tipsZh: "有缆车。秋叶壮观。",
    accessibilityFeatures: JSON.stringify(["Cable car", "Limited wheelchair access"]),
    isFeatured: true, isActive: true,
  },
  {
    nameEn: "Orange Island (Juzizhou)", nameZh: "橘子洲",
    descriptionEn: "Long island in Xiang River with Mao Zedong statue and scenic walking paths.",
    descriptionZh: "湘江中的长岛，毛泽东雕像和风景步道。",
    category: "Natural", location: "Changsha", city: "Changsha",
    openingHours: "7:00-22:00", averageDuration: "2-3 hours",
    ticketPrice: "0", currency: "USD", rating: "4.3",
    isRecommendedForPatients: true, tipsEn: "Weekend fireworks. Flat, scenic paths.",
    tipsZh: "周末烟花。平坦风景步道。",
    accessibilityFeatures: JSON.stringify(["Wheelchair accessible", "Flat surface", "Tram"]),
    isFeatured: false, isActive: true,
  },
];

async function seedExpandedAttractions() {
  try {
    console.log("🎡 Connecting to database...");
    const db = await getDb();

    console.log("📋 Checking existing data...");
    try {
      const existing = await db.select().from(attractions).limit(1);
      if (existing.length > 0) {
        console.log("⚠️ Clearing existing attractions...");
        await db.delete(attractions);
        console.log("✅ Cleared existing data");
      }
    } catch (e: any) {
      console.log("⚠️ Check failed, proceeding...");
    }

    console.log(`🎡 Creating ${EXPANDED_ATTRACTIONS.length} attractions...`);
    const inserted = await db.insert(attractions).values(EXPANDED_ATTRACTIONS).returning();

    // Stats
    const cityStats: Record<string, number> = {};
    const catStats: Record<string, number> = {};
    inserted.forEach(a => {
      cityStats[a.city] = (cityStats[a.city] || 0) + 1;
      if (a.category) catStats[a.category] = (catStats[a.category] || 0) + 1;
    });

    console.log(`\n📊 Summary: ${inserted.length} attractions across ${Object.keys(cityStats).length} cities`);
    console.log(`\n🏘️ By City:`);
    Object.entries(cityStats).sort((a, b) => b[1] - a[1]).forEach(([c, n]) => console.log(`   ${c}: ${n}`));
    console.log(`\n🎯 By Category:`);
    Object.entries(catStats).sort((a, b) => b[1] - a[1]).forEach(([c, n]) => console.log(`   ${c}: ${n}`));
    console.log(`\n✅ Attractions seeded successfully!`);
  } catch (error) {
    console.error("❌ Seed failed:", error);
    process.exit(1);
  }
}

seedExpandedAttractions().then(() => { process.exit(0); }).catch(e => { console.error(e); process.exit(1); });
